services:
  backup:
    build: .
    container_name: neon-backup
    env_file:
      - .env
    volumes:
      - ./backups:/backups
    restart: unless-stopped

#   postgres:
#     image: postgres:latest
#     container_name: postgres-db
#     restart: always
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   restore:
#     image: postgres:latest
#     container_name: restore-db
#     depends_on:
#       - backup
#     env_file:
#       - .env
#     volumes:
#       - ./backups:/backups
#     entrypoint: ["/bin/sh", "-c"]
#     command: ["/restore-script.sh"]

# volumes:
#   postgres_data:
