services:
  backup:
    build:
      context: .
      dockerfile: Dockerfile.backup
    container_name: pg-backup
    env_file:
      - .env
    volumes:
      - ./backups:/backups
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  restore:
    build:
      context: .
      dockerfile: Dockerfile.restore
    container_name: pg-restorer
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./backups:/backups
    restart: unless-stopped

volumes:
  postgres_data:
