FROM alpine:latest

# Installa il client PostgreSQL
RUN apk add --no-cache postgresql-client

# Copia lo script di restore e il cronjob
COPY restore-cron /etc/crontabs/root
COPY restore-script.sh /restore-script.sh

# Rendi eseguibile lo script
RUN chmod +x /restore-script.sh

# Avvia il cron daemon in foreground
CMD ["crond", "-f"]